name: dbt-airflow

x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: docker/Dockerfile
    target: dev
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Added recommended settings
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'false'
    AIRFLOW_HOME: /opt/airflow
    # DBT settings
    DBT_PROFILES_DIR: /opt/airflow/dbt
    DBT_PROJECT_DIR: /opt/airflow/dbt
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_PORT: ${POSTGRES_PORT}
  user: "${UID:-1000}"  # 기본값을 안전한 UID로 변경
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - ../airflow/dbt:/opt/airflow/dbt
  depends_on:
    postgres:
      condition: service_healthy
  healthcheck:
    test: ["CMD", "nc", "-z", "postgres", "5432"]
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbt-airflow-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  init:
    <<: *airflow-common
    command: |
      bash -c '
        airflow db init && \
        airflow users create \
          --username ${AIRFLOW_ADMIN_USER:-admin} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com} \
          --password ${AIRFLOW_ADMIN_PASSWORD}
      '
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure:3

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "18080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob", "--hostname", "scheduler"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully

  # FastAPI 서비스 추가
  api:
    <<: *airflow-common
    command: python /opt/airflow/simple_api.py
    ports:
      - "8004:8004"
    environment:
      <<: *airflow-env
      API_HOST: "0.0.0.0"
      API_PORT: "8004"
    volumes:
      - ../simple_api.py:/opt/airflow/simple_api.py
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully

  nginx-docs:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ../airflow/dbt/target:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  dbt-airflow-postgres:
