name: 'postgres_data_copy'
version: '1.0.0'

profile: 'postgres_data_copy'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

# dbt 버전 호환성 설정
require-dbt-version: ">=1.8.0"

# 프로젝트 설정
config-version: 2

# 모델 설정 - 태그 기반 그룹화로 선택적 실행 가능
models:
  postgres_data_copy:
    # 실제 비즈니스 모델들 - 현재 활성화
    business:
      +materialized: table
      +schema: business
      +tags: ["business", "production", "infomax"]
      +enabled: true

    # 향후 추가될 모델들을 위한 그룹
    future:
      +materialized: table
      +schema: future
      +tags: ["future", "development"]
      +enabled: false  # 기본적으로 비활성화

# 스냅샷 설정 - PostgreSQL 호환성 개선
snapshots:
  postgres_data_copy:
    +target_schema: snapshots
    +tags: ["snapshots"]
    +materialized: snapshot
    +strategy: check
