postgres_data_copy:  # this should match the profile name in your dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', '10.150.2.150') }}"
      user: "{{ env_var('POSTGRES_USER', 'airflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'airflow') }}"
      port: "{{ env_var('POSTGRES_PORT', 15432) }}"
      dbname: "{{ env_var('POSTGRES_DB', 'airflow') }}"
      schema: raw_data
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
